<?php
namespace app\index\controller;

use app\common\controller\Frontend;
use think\Controller;

class Base extends Frontend
{
	protected $cookie_expire = 604800;

	public function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->platform = get_platform(); // 获取当前平台  pc、app、weixin
		$this->assign('platform', $this->platform);
		//当前链接
		// 当前地址
		$this->current_url = 'http://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
		$current_action    = strtolower($this->request->action());
		// dump(strtolower($this->request->controller()) . '/' . $current_action);die;
		if ($this->platform != 'weixin') {
			//cookie('openid', 'osDgR1mzffRFc_qMvx0w86bNzTJU', $this->cookie_expire); //本地调试
		}
		//        cookie('openid', 'obL6dw7iSGTORMhSZYioIVYrWTG0', $this->cookie_expire); //本地调试
		//        cookie('user_id', 1, $this->cookie_expire); //本地调试
		switch ($this->platform) {
			case 'weixin':
				break;
			default:
				break;
		}
		$uid           = cookie('register_uid');
		$uid           = $uid ? $uid : cookie('login_uid');
		$openid        = cookie('openid');
		$this->openid  = $openid;
		$user_id       = cookie('user_id') ? cookie('user_id') : $uid;
		$user_id       = empty($user_id) ? 0 : (int) $user_id;
		$this->user_id = $user_id;
		$user_model = model('wxuser');
		$this->userInfo = $user_model->where('id', $this->user_id)->find();
		if (!in_array($current_action, ['auth_back', 'upload'])) {
			$this->is_auth(); // 微信授权登录
		}
		//        if ($openid) {
		//            // 每次获取微信用户信息 更新用户信息
		//            $wx_model = new \app\index\controller\Weixin();
		//            $wx_user = $wx_model->get_user_info($openid);
		//            if (isset($wx_user['subscribe']) && $wx_user['subscribe'] == 1) {
		//                cookie('attention', null);
		//            }
		//        }
		$referId = input('recUid', 0);
		$this->assign('recUid', $referId);
		$this->assign('user_id', $this->user_id);
		$this->assign('userInfo', $this->userInfo);
		$this->assign('usertotal', $user_model->count() ?: 0);
		$this->assign('usernew', $user_model->order('id', 'desc')->limit(3)->column('headimage'));
		$this->assign('yun_config', config('yun_url'));
		// 微信配置
		$jsapi = '';
		if ($this->platform == 'weixin') {
			// 分享配置
			$jsapi_config  = ['onMenuShareAppMessage', 'onMenuShareTimeline'];
			$cur_operation = strtolower($this->request->controller()).'/'.$current_action;
			// 上传图片配置
			if (in_array($cur_operation, ['sleeppu/write_dream', 'user/apply_teacher', 'live/live'])) {
				$jsapi_config = array_merge($jsapi_config, [
					'previewImage',
				]);
			}
			// 预览图片设置
			if (in_array($cur_operation, ['sleeppu/write_dream', 'members/info'])) {
				$jsapi_config = array_merge($jsapi_config, [
					'chooseImage',
					'uploadImage',
				]);
			}
			// 微信支付配置
			if (in_array($cur_operation, ['shop/detail', 'shop/account', 'shop/pay', 'member/myorders'])) {
				$jsapi_config = array_merge($jsapi_config, [
					'chooseWXPay',
					'previewImage',
				]);
			}
			$jsapi = action('index/Weixin/jsapi', [$jsapi_config]);
		}
		$this->assign('jsapi', $jsapi);
		//基本分享信息
		$wechatShare = [
			'title'  => config('site.share_title'),
			'desc'   => config('site.share_desc'),
			'imgUrl' => config('yun_url').config('site.share_image'),
			'link'   => '',
		];
		$this->assign('wechatShare', $wechatShare);
	}

	/**
	 * 用户登录检测
	 * @author jry <598821125@qq.com>
	 */
	protected function is_auth()
	{
		if (empty($this->openid)) {
			cookie('openid', null);
			cookie('user_id', null);
			$this->wechat();
			exit;
		} else {
			if (empty($this->userInfo) || $this->userInfo['openid'] != $this->openid) {
				cookie('openid', null);
				cookie('user_id', null);
				$this->wechat();
				exit;
			}
			return $this->user_id;
		}
	}

	public function wechat()
	{
		$cookie_time = $this->cookie_expire;
		cookie('target_url', $this->current_url, $cookie_time);
		/*  Url::root('/cityenglish/index.php');*/
		$back_url = url('index/Weixin/auth_back', null, false, true);
		action('index/Weixin/auth', [$back_url, 'snsapi_userinfo']);
	}
}
